#!/bin/bash
filepath="file://$(realpath "$1")"

osascript <<EOF
tell application "Google Chrome"
  set theURL to "$filepath"
  set tabFound to false
  set windowCount to count of windows

  repeat with wIndex from 1 to windowCount
    set w to window wIndex
    set tabCount to count of tabs of w
    repeat with tIndex from 1 to tabCount
      set t to tab tIndex of w
      if URL of t is equal to theURL then
        if (active tab index of w) is not equal to tIndex then
          set active tab index of w to tIndex
        end if
        set index of w to 1 -- bring window to front
        reload t
        set tabFound to true
        exit repeat
      end if
    end repeat
    if tabFound then exit repeat
  end repeat

  if not tabFound then
    tell window 1
      set newTab to make new tab with properties {URL:theURL}
      set active tab index to (get index of newTab)
    end tell
    set index of window 1 to 1 -- bring to front
  end if
  activate
end tell
EOF
